
paths:
  checkpoint_dir: checkpoints   # Directory to store model checkpoints and tensorboard, will be created if not existing.
  data_dir: datasets            # Directory to store processed data, will be created if not existing.

preprocessing:
  languages: ['ita', 'spa']    # All languages in the dataset.

  # Text (grapheme) and phoneme symbols, either provide a string or list of strings.
  # Symbols in the dataset will be filtered according to these lists!
  
  text_symbols: [
    'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j',
    'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
    'u', 'v', 'w', 'x', 'y', 'z', 'à', 'è', 'ì', 'ò',
    'ù', 'ü', 'á', 'é', 'í', 'ó', 'ú', 'ñ']

  phoneme_symbols: [
    'a', 'b', 'd', 'e', 'f', 'g', 'i', 'k', 'l', 'm',
    'n', 'o', 'p', 'r', 's', 't', 'u', 'β', 'ð', 'ɣ',
    'x', 'θ', 'ʝ', 'ɲ', 'ɾ', 'r', 'ʃ', 'ʎ', 'w', 'ç'
  ]

  char_repeats: 2                # Number of grapheme character repeats to allow for mapping to longer phoneme sequences.
                                 # Set to 1 for autoreg_transformer.
  lowercase: true                # Whether to lowercase the grapheme input.
  n_val: 5000                    # Default number of validation data points if no explicit validation data is provided.


model:
  type: 'transformer'            # Whether to use a forward transformer or autoregressive transformer model.
                                 # Choices: ['transformer', 'autoreg_transformer']
  d_model: 512
  d_fft: 1024
  layers: 6
  dropout: 0.1
  heads: 4

training:

  # Hyperparams for learning rate and scheduler.
  # The scheduler is reducing the lr on plateau of phoneme error rate (tested every n_generate_steps).

  learning_rate: 0.0003              # Learning rate of Adam.
  warmup_steps: 10000                # Linear increase of the lr from zero to the given lr within the given number of steps.
  scheduler_plateau_factor: 0.1      # Factor to multiply learning rate on plateau.
  scheduler_plateau_patience: 5      # Number of text generations with no improvement to tolerate.
  batch_size: 256                    # Training batch size.
  batch_size_val: 256                # Validation batch size.
  epochs: 300                        #
  generate_steps: 5000               #
  validate_steps: 5000               #
  checkpoint_steps: 50000            # 
  n_generate_samples: 10             # Number of result samples to show on tensorboard.
  store_phoneme_dict_in_model: true  # Whether to store the raw phoneme dict in the model.
                                     # It will be loaded by the phonemizer object.

  use_fp16: true
  ddp_backend: 'nccl'                # Backend used by Torch DDP
  ddp_host: 'localhost'              # Hostname used by Torch DDP
  ddp_post: '12355'                  # Port used by Torch DDP

dataloader:
  num_workers: 4
  pin_memory: true
