paths:
  checkpoint_dir: checkpoints/ita
  data_dir: datasets/ita

preprocessing:
  languages: ['ita']

  text_symbols: [
    'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l',
    'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'x', 'y',
    'z', 'à', 'á', 'è', 'é', 'ì', 'ò', 'ó', 'ù', 'ú'
  ]

  phoneme_symbols:  [
    'a', 'b', 'd', 'e', 'f', 'i', 'j', 'k', 'l', 'm', 'n', 'o',
    'p', 'r', 's', 't', 'u', 'v', 'w', 'z', 'ɔ', 'ɛ', 'ɡ', 'ɲ',
    'ʃ', 'ʎ', 'ʒ'
  ]
  
  char_repeats: 2
  lowercase: true
  n_val: 5000

model:
  type: 'transformer'
  d_model: 512
  d_fft: 1024
  layers: 6
  dropout: 0.1
  heads: 4

training:
  learning_rate: 0.0003
  warmup_steps: 10000
  scheduler_plateau_factor: 0.1
  scheduler_plateau_patience: 5
  batch_size: 256
  batch_size_val: 256
  epochs: 300
  generate_steps: 5000
  validate_steps: 5000
  checkpoint_steps: 50000
  n_generate_samples: 10
  store_phoneme_dict_in_model: true
  use_fp16: true
  ddp_backend: 'nccl'
  ddp_host: 'localhost'
  ddp_post: '12355'

dataloader:
  num_workers: 4
  pin_memory: true
